[package]
name = "faves"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
include_dir = "0.7.3"
log = "0.4.17"
serde_json = "1.0.88"
wasm-logger = "0.2.0"
yew = "0.19.3"
yew-router = "0.16.0"